/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetopi2.views;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import com.mycompany.projetopi2.dao.ProdutoDAO;
import com.mycompany.projetopi2.models.Produto;

/**
 *
 * @author joser
 */
public class PRO_ConsultaProdutos extends javax.swing.JFrame {

    /**
     * Creates new form PRO_ConsultaProdutos
     */
    public PRO_ConsultaProdutos() {
        initComponents();
        pnl_Descricao.setVisible(false);
        carregarProdutos(ProdutoDAO.listarProdutos());
    }

    private void carregarProdutos(ArrayList<Produto> produtos) {

        DefaultTableModel modelo = (DefaultTableModel) tbl_ConsultaProduto.getModel();
        modelo.setNumRows(0);

        for (Produto produto : produtos) {
            modelo.addRow(new String[]{
                produto.getCodProduto(),
                produto.getNome(),
                produto.getCategoria(),
                produto.getUnidadeVenda(),
                Double.toString(produto.getValor()),
                Integer.toString(produto.getQuantidade())
            });
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ConsultaProduto = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txt_Pesquisar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbx_Categoria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btn_Consulta = new javax.swing.JButton();
        btn_AdicionarProduto = new javax.swing.JButton();
        btn_RemoverProduto = new javax.swing.JButton();
        pnl_Descricao = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Descricao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Produto");
        setAlwaysOnTop(true);

        tbl_ConsultaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD.", "NOME", "CATEGORIA", "TIPO", "VALOR", "QTD ESTOQUE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_ConsultaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ConsultaProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_ConsultaProduto);
        if (tbl_ConsultaProduto.getColumnModel().getColumnCount() > 0) {
            tbl_ConsultaProduto.getColumnModel().getColumn(0).setResizable(false);
            tbl_ConsultaProduto.getColumnModel().getColumn(0).setPreferredWidth(25);
            tbl_ConsultaProduto.getColumnModel().getColumn(1).setResizable(false);
            tbl_ConsultaProduto.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar"));

        txt_Pesquisar.setToolTipText("");
        txt_Pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PesquisarKeyTyped(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/8673694_ic_fluent_search_filled_icon.png"))); // NOI18N

        cbx_Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Medicamento", "Higiene", "Cosméticos", "Acessórios", "Suplementos e Vitaminicos" }));
        cbx_Categoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_CategoriaItemStateChanged(evt);
            }
        });

        jLabel2.setText("Categoria");

        btn_Consulta.setText("Buscar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txt_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Consulta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbx_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(btn_Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btn_AdicionarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/8672677_ic_fluent_add_filled_icon.png"))); // NOI18N
        btn_AdicionarProduto.setToolTipText("Adicionar");
        btn_AdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AdicionarProdutoActionPerformed(evt);
            }
        });

        btn_RemoverProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/8673137_ic_fluent_dismiss_filled_icon.png"))); // NOI18N
        btn_RemoverProduto.setToolTipText("Remover");
        btn_RemoverProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RemoverProdutoActionPerformed(evt);
            }
        });

        pnl_Descricao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESCRIÇÃO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        txt_Descricao.setEditable(false);
        txt_Descricao.setColumns(20);
        txt_Descricao.setRows(5);
        jScrollPane2.setViewportView(txt_Descricao);

        javax.swing.GroupLayout pnl_DescricaoLayout = new javax.swing.GroupLayout(pnl_Descricao);
        pnl_Descricao.setLayout(pnl_DescricaoLayout);
        pnl_DescricaoLayout.setHorizontalGroup(
            pnl_DescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
        );
        pnl_DescricaoLayout.setVerticalGroup(
            pnl_DescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_DescricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnl_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_AdicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_RemoverProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_RemoverProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(btn_AdicionarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdicionarProdutoActionPerformed
        PRO_AdicionarProdutos proAdd = new PRO_AdicionarProdutos();
        proAdd.setVisible(true);
        proAdd.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_AdicionarProdutoActionPerformed

    private void tbl_ConsultaProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ConsultaProdutoMouseClicked
        // TODO add your handling code here:
        exibirDescricao();
    }//GEN-LAST:event_tbl_ConsultaProdutoMouseClicked

    private void cbx_CategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_CategoriaItemStateChanged
        // TODO add your handling code here:

        String categoria = cbx_Categoria.getSelectedItem().toString();

        if (categoria.equals("Todas")) {
            carregarProdutos(ProdutoDAO.listarProdutos());
        } else {
            ArrayList<Produto> listaProdutos = ProdutoDAO.pesquisarPorCategoria(categoria);            
            carregarProdutos(listaProdutos);
        }
    }//GEN-LAST:event_cbx_CategoriaItemStateChanged

    private void txt_PesquisarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PesquisarKeyTyped
        // TODO add your handling code here:
        String busca = txt_Pesquisar.getText();
        String categoria = cbx_Categoria.getSelectedItem().toString();

        if (categoria.equals("Todas")) {
            ArrayList<Produto> listaProdutos = ProdutoDAO.pesquisarPorNome(busca);
            carregarProdutos(listaProdutos);
        } else {
            ArrayList<Produto> listaProdutos = ProdutoDAO.pesquisarPorNomeECategoria(busca, categoria);
            carregarProdutos(listaProdutos);
        }

    }//GEN-LAST:event_txt_PesquisarKeyTyped

    private void btn_RemoverProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RemoverProdutoActionPerformed
        // TODO add your handling code here:
        int linha = tbl_ConsultaProduto.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um produto para remover!");
        } else {
            String codigo = tbl_ConsultaProduto.getValueAt(linha, 0).toString();
            String nome = tbl_ConsultaProduto.getValueAt(linha, 1).toString();

            int opcao = JOptionPane.showConfirmDialog(this, "Deseja remover o produto " + nome + "?");

            if (opcao == 0) {
                boolean sucesso = ProdutoDAO.removerProduto(codigo);
                if (sucesso) {
                    JOptionPane.showMessageDialog(this, "Produto removido com sucesso!");
                    carregarProdutos(ProdutoDAO.listarProdutos());
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao remover produto!");
                }

            }
        }



    }//GEN-LAST:event_btn_RemoverProdutoActionPerformed

    private void exibirDescricao() {
        pnl_Descricao.setVisible(true);

        int linha = tbl_ConsultaProduto.getSelectedRow();
        String codigo = tbl_ConsultaProduto.getValueAt(linha, 0).toString();

        String descricao = ProdutoDAO.exibirDescricao(codigo);

        txt_Descricao.setText(descricao);
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRO_ConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRO_ConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRO_ConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRO_ConsultaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRO_ConsultaProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AdicionarProduto;
    private javax.swing.JButton btn_Consulta;
    private javax.swing.JButton btn_RemoverProduto;
    private javax.swing.JComboBox<String> cbx_Categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnl_Descricao;
    private javax.swing.JTable tbl_ConsultaProduto;
    private javax.swing.JTextArea txt_Descricao;
    private javax.swing.JTextField txt_Pesquisar;
    // End of variables declaration//GEN-END:variables
}
