CREATE SCHEMA IF NOT EXISTS Farmacia;

USE Farmacia;

CREATE TABLE IF NOT EXISTS Cliente(

	IDCliente INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Nome VARCHAR(50) NOT NULL,
	Sexo VARCHAR(10) NOT NULL,
	DataNascimento DATE NOT NULL,
	EstadoCivil VARCHAR(20) NOT NULL,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	Telefone VARCHAR(11) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Endereco VARCHAR(50) NOT NULL

);

CREATE TABLE IF NOT EXISTS Produto(

	IDProduto INT NOT NULL AUTO_INCREMENT,
	Nome VARCHAR(50) NOT NULL,
	CodProduto INT NOT NULL UNIQUE,
	Categoria VARCHAR(50) NOT NULL,
	Preco DECIMAL(10,2) NOT NULL,
	UnidadeVenda VARCHAR(10) NOT NULL,
	Quantidade INT NOT NULL,
	Descricao VARCHAR(100) NOT NULL

);

CREATE TABLE IF NOT EXISTS Venda(

	IDVenda INT NOT NULL AUTO_INCREMENT,
	IDCliente INT NOT NULL,
	DataVenda DATE NOT NULL,
	Quantidade INT NOT NULL,
	ValorTotal DECIMAL(10,2) NOT NULL,

	PRIMARY KEY(IDVenda),
	FOREIGN KEY(IDCliente) REFERENCES Cliente(IDCliente)

);

CREATE TABLE IF NOT EXISTS ItemVenda(

	IDItemVenda INT NOT NULL AUTO_INCREMENT,
	IDVenda INT NOT NULL,
	NumItem INT NOT NULL,
	IDProduto INT NOT NULL,
	Quantidade INT NOT NULL,
	ValorTotal DECIMAL(10,2) NOT NULL,

	PRIMARY KEY(IDItemVenda),
	FOREIGN KEY(IDVenda) REFERENCES Venda(IDVenda),
	FOREIGN KEY(IDProduto) REFERENCES Produto(IDProduto)

);